{
  "image": "node:8",
  "stages": [
    "test",
    "deploy"
  ],
  "test": {
    "stage": "test",
    "artifacts": {
      "paths": [
        "node_modules/"
      ]
    },
    "script": [
      "npm install",
      "npm test"
    ],
    "except": [
      "pages"
    ]
  },
  "publish": {
    "stage": "deploy",
    "dependencies": [
      "test"
    ],
    "script": [
      "./script/update.js"
    ],
    "environment": "npm",
    "only": [
      "master"
    ]
  },
  "pages": {
    "stage": "deploy",
    "dependencies": [
      "test"
    ],
    "script": [
      "npm run pages"
    ],
    "environment": "pages",
    "artifacts": {
      "paths": [
        "public"
      ]
    },
    "only": [
      "master"
    ]
  }
}
